### PR TITLE
Experimental h264

### PR DESCRIPTION
**Pull request by linlin4426**
where is main.js? It seems no main.js in project.

### CODE REVIEW

**Comment by martin19** [comment]
@linlin4426 I'll have a look. Maybe I forgot adding it.

**Comment by martin19** [comment]
ok, to summarize: this is a typescript conversion of novnc code and integration of a h264 decoder.
noVNC is javascript and I wanted it to be typescript.
There is a webpack build which creates the main.js file in the dist folder. If you set everything up correctly it should work with
https://github.com/martin19/libvncserver/tree/experimental. I have stopped working on this - so it remained on experimental.

**Comment by martin19** [comment]
@linlin4426 put up a small readme.. happy tinkering!

**Comment by linlin4426** [comment]
> ok, to summarize: this is a typescript conversion of novnc code and integration of a h264 decoder. noVNC is javascript and I wanted it to be typescript. There is a webpack build which creates the main.js file in the dist folder. If you set everything up correctly it should work with https://github.com/martin19/libvncserver/tree/experimental. I have stopped working on this - so it remained on experimental.

thanks for your reply, and i will have a try

**Pull request merged**
